// <auto-generated />
using System;
using Batates.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Batates.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Batates.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<int>("CartID")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Fullname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Gender")
                        .HasColumnType("int");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "8e445865-a24d-4543-a6c6-9443d048cdb9",
                            AccessFailedCount = 0,
                            CartID = 0,
                            ConcurrencyStamp = "ad6a50f6-6a25-4333-9a5f-4d711baf13ea",
                            Email = "admin@batates.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@BATATES.COM",
                            NormalizedUserName = "ADMIN@BATATES",
                            PasswordHash = "AQAAAAIAAYagAAAAEFxsX8a1SXs0lOYgazzSdgFImTad1nRLmwzhcnm/4wG3v+9JhC8tPFteoN2gp+IfeQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "366f00af-f16f-4f4b-ba90-7489ab9606a4",
                            TwoFactorEnabled = false,
                            UserName = "admin@batates.com"
                        },
                        new
                        {
                            Id = "2097f2ca-02a2-4b4f-97a0-1a7679151295",
                            AccessFailedCount = 0,
                            CartID = 0,
                            ConcurrencyStamp = "2873a2c8-7485-4473-9dfe-5e51ac0cd123",
                            Email = "customer@batates.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "CUSTOMER@BATATES.COM",
                            NormalizedUserName = "CUSTOMER@BATATES",
                            PasswordHash = "AQAAAAIAAYagAAAAENWiBqTuCpcOgKyGMPI4aiW3zzL8pPhonIAc8dXLZglNHhwRghSo0Akjxdo4lqIbyA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "f10fc074-d88a-4e3f-93e4-59eb5e71f75c",
                            TwoFactorEnabled = false,
                            UserName = "customer@batates.com"
                        });
                });

            modelBuilder.Entity("Batates.Models.Cart", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("ApplicationUserID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ID");

                    b.HasIndex("ApplicationUserID")
                        .IsUnique();

                    b.ToTable("Carts", (string)null);
                });

            modelBuilder.Entity("Batates.Models.CartProduct", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("CartID")
                        .HasColumnType("int");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CartID");

                    b.HasIndex("ProductID");

                    b.ToTable("CartProduct", (string)null);
                });

            modelBuilder.Entity("Batates.Models.Category", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Category", (string)null);

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Description = "Indulge in the rich flavors and culinary heritage of Italy with our authentic Italian cuisine, where every dish is crafted with passion and tradition to transport you to the sun-kissed hills of Tuscany and the bustling streets of Naples.",
                            ImageURL = "https://dummyjson.com/image/512x512/?text=Italian",
                            Name = "Italian"
                        },
                        new
                        {
                            ID = 2,
                            Description = "Experience the vibrant and spicy flavors of Mexico with our tantalizing Mexican cuisine, from sizzling fajitas to mouthwatering tacos, guaranteed to ignite your taste buds with every bite.",
                            ImageURL = "https://dummyjson.com/image/512x512/?text=Mexican",
                            Name = "Mexican"
                        },
                        new
                        {
                            ID = 3,
                            Description = "Embark on a culinary journey to Japan with our exquisite Japanese cuisine, where tradition meets innovation in every carefully crafted sushi roll, flavorful ramen bowl, and delicate tempura dish.",
                            ImageURL = "https://dummyjson.com/image/512x512/?text=Japanese",
                            Name = "Japanese"
                        },
                        new
                        {
                            ID = 4,
                            Description = "Delight your senses with the aromatic spices and diverse flavors of India through our authentic Indian cuisine, featuring savory curries, aromatic biryanis, and decadent desserts that will transport you to the bustling streets of Mumbai and the serene backwaters of Kerala.",
                            ImageURL = "https://dummyjson.com/image/512x512/?text=Indian",
                            Name = "Indian"
                        });
                });

            modelBuilder.Entity("Batates.Models.Order", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("ApplicationUserID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("int");

                    b.Property<double>("TotalPrice")
                        .HasColumnType("float");

                    b.HasKey("ID");

                    b.HasIndex("ApplicationUserID");

                    b.ToTable("Orders", (string)null);
                });

            modelBuilder.Entity("Batates.Models.OrderProduct", b =>
                {
                    b.Property<int>("OrderID")
                        .HasColumnType("int");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("OrderID", "ProductID");

                    b.HasIndex("ProductID");

                    b.ToTable("OrderProduct", (string)null);
                });

            modelBuilder.Entity("Batates.Models.Product", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExtraDetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("RestaurantID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("RestaurantID");

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Description = "Best Pizza slice in the world",
                            ImageURL = "https://dummyjson.com/image/512x512/?text=Pizza+Slice",
                            Name = "One Pizza Slice",
                            Price = 9.9900000000000002,
                            RestaurantID = 1
                        },
                        new
                        {
                            ID = 2,
                            Description = "Best Entire Pizza in the world",
                            ImageURL = "https://dummyjson.com/image/512x512/?text=Entire+Pizza",
                            Name = "One Pizza",
                            Price = 9.9900000000000002,
                            RestaurantID = 1
                        },
                        new
                        {
                            ID = 3,
                            Description = "A delicious vegetarian pizza",
                            ImageURL = "https://dummyjson.com/image/512x512/?text=Vegetarian+Pizza",
                            Name = "Vegetarian Pizza",
                            Price = 11.99,
                            RestaurantID = 1
                        },
                        new
                        {
                            ID = 4,
                            Description = "Classic pepperoni pizza",
                            ImageURL = "https://dummyjson.com/image/512x512/?text=Pepperoni+Pizza",
                            Name = "Pepperoni Pizza",
                            Price = 12.99,
                            RestaurantID = 1
                        },
                        new
                        {
                            ID = 5,
                            Description = "Traditional margherita pizza",
                            ImageURL = "https://dummyjson.com/image/512x512/?text=Margherita+Pizza",
                            Name = "Margherita Pizza",
                            Price = 10.99,
                            RestaurantID = 1
                        },
                        new
                        {
                            ID = 6,
                            Description = "Classic Italian pasta dish with creamy carbonara sauce, pancetta, and Parmesan cheese",
                            ImageURL = "https://dummyjson.com/image/512x512/?text=Spaghetti+Carbonara",
                            Name = "Spaghetti Carbonara",
                            Price = 14.99,
                            RestaurantID = 2
                        },
                        new
                        {
                            ID = 7,
                            Description = "Homemade ravioli filled with ricotta cheese, served with a flavorful tomato sauce",
                            ImageURL = "https://dummyjson.com/image/512x512/?text=Ravioli+al+Pomodoro",
                            Name = "Ravioli al Pomodoro",
                            Price = 16.989999999999998,
                            RestaurantID = 2
                        },
                        new
                        {
                            ID = 8,
                            Description = "Classic Italian dessert made with layers of coffee-soaked ladyfingers and mascarpone cheese, dusted with cocoa powder",
                            ImageURL = "https://dummyjson.com/image/512x512/?text=Tiramisu",
                            Name = "Tiramisu",
                            Price = 8.9900000000000002,
                            RestaurantID = 2
                        },
                        new
                        {
                            ID = 9,
                            Description = "Fresh salad made with ripe tomatoes, mozzarella cheese, basil, and balsamic glaze",
                            ImageURL = "https://dummyjson.com/image/512x512/?text=Caprese+Salad",
                            Name = "Caprese Salad",
                            Price = 9.9900000000000002,
                            RestaurantID = 2
                        },
                        new
                        {
                            ID = 10,
                            Description = "Creamy fettuccine pasta tossed in a rich Alfredo sauce made with butter, cream, and Parmesan cheese",
                            ImageURL = "https://dummyjson.com/image/512x512/?text=Fettuccine+Alfredo",
                            Name = "Fettuccine Alfredo",
                            Price = 13.99,
                            RestaurantID = 2
                        },
                        new
                        {
                            ID = 11,
                            Description = "A supreme taco filled with seasoned beef, lettuce, cheese, tomatoes, and sour cream, served in a crispy corn shell",
                            ImageURL = "https://dummyjson.com/image/512x512/?text=Taco+Supreme",
                            Name = "Taco Supreme",
                            Price = 3.9900000000000002,
                            RestaurantID = 6
                        },
                        new
                        {
                            ID = 12,
                            Description = "A hearty burrito filled with tender grilled chicken, rice, beans, cheese, and salsa, wrapped in a warm flour tortilla",
                            ImageURL = "https://dummyjson.com/image/512x512/?text=Chicken+Burrito",
                            Name = "Chicken Burrito",
                            Price = 8.9900000000000002,
                            RestaurantID = 6
                        },
                        new
                        {
                            ID = 13,
                            Description = "A comforting bowl of chili made with ground beef, beans, tomatoes, and spices, topped with cheese and onions",
                            ImageURL = "https://dummyjson.com/image/512x512/?text=Chili+Con+Carne",
                            Name = "Chili Con Carne",
                            Price = 6.9900000000000002,
                            RestaurantID = 6
                        },
                        new
                        {
                            ID = 14,
                            Description = "A cheesy quesadilla filled with melted cheese and your choice of chicken, beef, or vegetables, served with salsa and sour cream",
                            ImageURL = "https://dummyjson.com/image/512x512/?text=Quesadilla",
                            Name = "Quesadilla",
                            Price = 7.9900000000000002,
                            RestaurantID = 6
                        },
                        new
                        {
                            ID = 15,
                            Description = "A supreme platter of nachos topped with seasoned beef, melted cheese, jalapenos, tomatoes, and sour cream, perfect for sharing",
                            ImageURL = "https://dummyjson.com/image/512x512/?text=Nachos+Supreme",
                            Name = "Nachos Supreme",
                            Price = 10.99,
                            RestaurantID = 6
                        },
                        new
                        {
                            ID = 16,
                            Description = "An exquisite platter of assorted sushi, featuring a variety of nigiri and maki rolls made with fresh fish and seasoned rice",
                            ImageURL = "https://dummyjson.com/image/512x512/?text=Sushi+Platter",
                            Name = "Sushi Platter",
                            Price = 24.989999999999998,
                            RestaurantID = 11
                        },
                        new
                        {
                            ID = 17,
                            Description = "A crispy tempura shrimp roll wrapped in seaweed and rice, served with soy sauce and wasabi for dipping",
                            ImageURL = "https://dummyjson.com/image/512x512/?text=Tempura+Shrimp+Roll",
                            Name = "Tempura Shrimp Roll",
                            Price = 12.99,
                            RestaurantID = 11
                        },
                        new
                        {
                            ID = 18,
                            Description = "A delectable sampler of fresh sashimi slices, including tuna, salmon, and yellowtail, served with pickled ginger and wasabi",
                            ImageURL = "https://dummyjson.com/image/512x512/?text=Sashimi+Sampler",
                            Name = "Sashimi Sampler",
                            Price = 18.989999999999998,
                            RestaurantID = 11
                        },
                        new
                        {
                            ID = 19,
                            Description = "A comforting bowl of udon noodles in a savory broth, topped with sliced green onions, tempura flakes, and a seasoned boiled egg",
                            ImageURL = "https://dummyjson.com/image/512x512/?text=Udon+Noodle+Soup",
                            Name = "Udon Noodle Soup",
                            Price = 10.99,
                            RestaurantID = 11
                        },
                        new
                        {
                            ID = 20,
                            Description = "A traditional Japanese bento box featuring teriyaki chicken, steamed rice, vegetable tempura, and a side of miso soup",
                            ImageURL = "https://dummyjson.com/image/512x512/?text=Teriyaki+Chicken+Bento+Box",
                            Name = "Teriyaki Chicken Bento Box",
                            Price = 16.989999999999998,
                            RestaurantID = 11
                        },
                        new
                        {
                            ID = 21,
                            Description = "Tender pieces of grilled chicken cooked in a creamy tomato-based sauce with aromatic Indian spices, served with basmati rice",
                            ImageURL = "https://dummyjson.com/image/512x512/?text=Chicken+Tikka+Masala",
                            Name = "Chicken Tikka Masala",
                            Price = 14.99,
                            RestaurantID = 16
                        },
                        new
                        {
                            ID = 22,
                            Description = "Fragrant basmati rice cooked with mixed vegetables, herbs, and spices, served with raita and papadum",
                            ImageURL = "https://dummyjson.com/image/512x512/?text=Vegetable+Biryani",
                            Name = "Vegetable Biryani",
                            Price = 12.99,
                            RestaurantID = 16
                        },
                        new
                        {
                            ID = 23,
                            Description = "Soft cubes of paneer cheese cooked in a rich and creamy tomato-based sauce, flavored with butter and aromatic spices, served with naan bread",
                            ImageURL = "https://dummyjson.com/image/512x512/?text=Paneer+Butter+Masala",
                            Name = "Paneer Butter Masala",
                            Price = 13.99,
                            RestaurantID = 16
                        },
                        new
                        {
                            ID = 24,
                            Description = "Yellow lentils cooked with onions, tomatoes, garlic, and cumin seeds, tempered with ghee and garnished with fresh cilantro, served with rice or naan",
                            ImageURL = "https://dummyjson.com/image/512x512/?text=Dal+Tadka",
                            Name = "Dal Tadka",
                            Price = 9.9900000000000002,
                            RestaurantID = 16
                        },
                        new
                        {
                            ID = 25,
                            Description = "Soft and spongy milk dumplings soaked in a sweet rose-flavored syrup, served warm and garnished with chopped pistachios",
                            ImageURL = "https://dummyjson.com/image/512x512/?text=Gulab+Jamun",
                            Name = "Gulab Jamun",
                            Price = 6.9900000000000002,
                            RestaurantID = 16
                        });
                });

            modelBuilder.Entity("Batates.Models.Restaurant", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("ContactNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Restaurant", (string)null);

                    b.HasData(
                        new
                        {
                            ID = 1,
                            ContactNo = "0114379314",
                            Description = "Our mission is to uphold the highest level of quality in all we do, from the quality and origin of our food to our care for the health of our customers and the environment.",
                            Name = "RomaPizza",
                            State = 3
                        },
                        new
                        {
                            ID = 2,
                            ContactNo = "0215896347",
                            Description = "Experience the authentic flavors of Italy with our handcrafted pizzas, pasta, and mouthwatering desserts, served with a touch of Italian hospitality.",
                            Name = "Taste of Italy",
                            State = 3
                        },
                        new
                        {
                            ID = 3,
                            ContactNo = "0317269854",
                            Description = "Get ready for a fiesta of flavors with our bold and delicious Mexican cuisine, featuring tacos, burritos, and sizzling fajitas that will transport you south of the border.",
                            Name = "El Taco Loco",
                            State = 3
                        },
                        new
                        {
                            ID = 4,
                            ContactNo = "0413785621",
                            Description = "Discover the art of sushi at Sushi Zen, where our skilled chefs combine fresh ingredients with precision and technique to create sushi rolls that are as beautiful as they are delicious.",
                            Name = "Sushi Zen",
                            State = 3
                        },
                        new
                        {
                            ID = 5,
                            ContactNo = "0518932746",
                            Description = "Embark on a culinary journey through the flavors of India at Spice Route, where our aromatic spices and authentic recipes will tantalize your taste buds and transport you to the streets of Mumbai.",
                            Name = "Spice Route",
                            State = 3
                        },
                        new
                        {
                            ID = 6,
                            ContactNo = "1112345678",
                            Description = "Dance your taste buds to the rhythm of Mexico with Taco Tango, where our bold flavors and festive atmosphere will spice up your dining experience.",
                            Name = "Taco Tango",
                            State = 3
                        },
                        new
                        {
                            ID = 7,
                            ContactNo = "1212345678",
                            Description = "Wrap yourself in flavor with Burrito Bar, where our customizable burritos and fresh ingredients will satisfy your cravings for authentic Mexican cuisine.",
                            Name = "Burrito Bar",
                            State = 3
                        },
                        new
                        {
                            ID = 8,
                            ContactNo = "1312345678",
                            Description = "Join the fiesta at Fiesta Grill, where our sizzling fajitas, flavorful tacos, and refreshing margaritas will transport you straight to the heart of Mexico.",
                            Name = "Fiesta Grill",
                            State = 3
                        },
                        new
                        {
                            ID = 9,
                            ContactNo = "1412345678",
                            Description = "Heat up your night at Cantina Caliente, where our spicy dishes and lively atmosphere will make every meal feel like a celebration.",
                            Name = "Cantina Caliente",
                            State = 3
                        },
                        new
                        {
                            ID = 10,
                            ContactNo = "1512345678",
                            Description = "Take a trip down Salsa Street for a taste of authentic Mexican street food, where our vibrant flavors and casual setting will keep you coming back for more.",
                            Name = "Salsa Street",
                            State = 3
                        },
                        new
                        {
                            ID = 11,
                            ContactNo = "1612345678",
                            Description = "Experience sushi perfection at Sushi Supreme, where our expert chefs use only the freshest ingredients to create sushi rolls that are as beautiful as they are delicious.",
                            Name = "Sushi Supreme",
                            State = 3
                        },
                        new
                        {
                            ID = 12,
                            ContactNo = "1712345678",
                            Description = "Find your zen at Sakura Sushi Bar, where our serene ambiance and exquisite sushi creations will transport you to the tranquil gardens of Japan.",
                            Name = "Sakura Sushi Bar",
                            State = 3
                        },
                        new
                        {
                            ID = 13,
                            ContactNo = "1812345678",
                            Description = "Unleash your inner ninja at Ninja Noodles, where our bold flavors and innovative noodle dishes will satisfy your cravings for authentic Japanese cuisine.",
                            Name = "Ninja Noodles",
                            State = 3
                        },
                        new
                        {
                            ID = 14,
                            ContactNo = "1912345678",
                            Description = "Experience the excitement of teppanyaki dining at Tokyo Teppanyaki, where our skilled chefs entertain and delight you with their culinary prowess.",
                            Name = "Tokyo Teppanyaki",
                            State = 3
                        },
                        new
                        {
                            ID = 15,
                            ContactNo = "2012345678",
                            Description = "Journey into the world of wasabi at Wasabi Wonderland, where our bold flavors and creative sushi rolls will awaken your senses and transport you to a land of culinary adventure.",
                            Name = "Wasabi Wonderland",
                            State = 3
                        },
                        new
                        {
                            ID = 16,
                            ContactNo = "2112345678",
                            Description = "Spice up your life at Curry Corner, where our aromatic curries and flavorful Indian dishes will take your taste buds on a journey to the vibrant streets of India.",
                            Name = "Curry Corner",
                            State = 3
                        },
                        new
                        {
                            ID = 17,
                            ContactNo = "2212345678",
                            Description = "Experience the flavors of the tandoor at Tandoori Terrace, where our smoky grilled meats and tender breads will transport you to the bustling markets of Delhi.",
                            Name = "Tandoori Terrace",
                            State = 3
                        },
                        new
                        {
                            ID = 18,
                            ContactNo = "2312345678",
                            Description = "Savor the rich flavors of India with Biryani Bazaar, where our fragrant rice dishes and succulent meats are cooked to perfection and served with love.",
                            Name = "Biryani Bazaar",
                            State = 3
                        },
                        new
                        {
                            ID = 19,
                            ContactNo = "2412345678",
                            Description = "Experience the magic of Indian spices at Masala Magic, where our flavorful curries, aromatic biryanis, and decadent desserts will transport you to the colorful streets of Mumbai.",
                            Name = "Masala Magic",
                            State = 3
                        },
                        new
                        {
                            ID = 20,
                            ContactNo = "2512345678",
                            Description = "Find your nirvana at Naan Nirvana, where our soft and fluffy naan breads and savory accompaniments will elevate your dining experience to new heights.",
                            Name = "Naan Nirvana",
                            State = 3
                        });
                });

            modelBuilder.Entity("Batates.Models.WishedItem", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<int?>("WishlistID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ProductID");

                    b.HasIndex("WishlistID");

                    b.ToTable("WishedItem", (string)null);
                });

            modelBuilder.Entity("Batates.Models.Wishlist", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("ApplicationUserID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ID");

                    b.HasIndex("ApplicationUserID");

                    b.ToTable("Wishlists", (string)null);
                });

            modelBuilder.Entity("CategoryRestaurant", b =>
                {
                    b.Property<int>("CategoriesID")
                        .HasColumnType("int");

                    b.Property<int>("RestaurantsID")
                        .HasColumnType("int");

                    b.HasKey("CategoriesID", "RestaurantsID");

                    b.HasIndex("RestaurantsID");

                    b.ToTable("CategoryRestaurant", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "2c5e174e-3b0e-446f-86af-483d56fd7210",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "d3c902cf-6b3e-4f66-9b82-c6a18a4ffa13",
                            Name = "Customer",
                            NormalizedName = "CUSTOMER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "8e445865-a24d-4543-a6c6-9443d048cdb9",
                            RoleId = "2c5e174e-3b0e-446f-86af-483d56fd7210"
                        },
                        new
                        {
                            UserId = "2097f2ca-02a2-4b4f-97a0-1a7679151295",
                            RoleId = "d3c902cf-6b3e-4f66-9b82-c6a18a4ffa13"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Batates.Models.Cart", b =>
                {
                    b.HasOne("Batates.Models.ApplicationUser", "ApplicationUser")
                        .WithOne("Cart")
                        .HasForeignKey("Batates.Models.Cart", "ApplicationUserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("Batates.Models.CartProduct", b =>
                {
                    b.HasOne("Batates.Models.Cart", null)
                        .WithMany("Products")
                        .HasForeignKey("CartID");

                    b.HasOne("Batates.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Batates.Models.Order", b =>
                {
                    b.HasOne("Batates.Models.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("Batates.Models.OrderProduct", b =>
                {
                    b.HasOne("Batates.Models.Order", "Order")
                        .WithMany("OrderProducts")
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Batates.Models.Product", "Product")
                        .WithMany("OrderProducts")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Batates.Models.Product", b =>
                {
                    b.HasOne("Batates.Models.Restaurant", "Restaurant")
                        .WithMany("Products")
                        .HasForeignKey("RestaurantID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("Batates.Models.WishedItem", b =>
                {
                    b.HasOne("Batates.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Batates.Models.Wishlist", null)
                        .WithMany("WishedProducts")
                        .HasForeignKey("WishlistID");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Batates.Models.Wishlist", b =>
                {
                    b.HasOne("Batates.Models.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("CategoryRestaurant", b =>
                {
                    b.HasOne("Batates.Models.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoriesID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Batates.Models.Restaurant", null)
                        .WithMany()
                        .HasForeignKey("RestaurantsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Batates.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Batates.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Batates.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Batates.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Batates.Models.ApplicationUser", b =>
                {
                    b.Navigation("Cart");
                });

            modelBuilder.Entity("Batates.Models.Cart", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Batates.Models.Order", b =>
                {
                    b.Navigation("OrderProducts");
                });

            modelBuilder.Entity("Batates.Models.Product", b =>
                {
                    b.Navigation("OrderProducts");
                });

            modelBuilder.Entity("Batates.Models.Restaurant", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Batates.Models.Wishlist", b =>
                {
                    b.Navigation("WishedProducts");
                });
#pragma warning restore 612, 618
        }
    }
}
